services:
  app:
    build: .
    ports:
      - "5000:5000"
#      - "443:443"
    depends_on:
      - mysql
    environment:
#      DB_HOST: mysql
#      DB_USER: root
#      DB_PASSWORD: db-password
#      DB_NAME: scrpy01
      FLASK_ENV=: development
    networks:
      - app-network

  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: db-password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge