# Dockerfile

# Use the official Python image from the slim family
FROM python:3.11-slim

LABEL authors="Andesec"

# Set environment variables
ENV PYTHONUNBUFFERED=1 \
    FLASK_APP=scr101

# Set work directory
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . .

# Install any needed packages specified in requirements.txt
RUN pip install -r requirements.txt

# Make port 5000 available to the world outside this container
EXPOSE 5000

# Run app.py when the container launches
CMD ["flask", "run", "--host=0.0.0.0"]